WITH ELEME_LISTESI AS (  
SELECT /*+PARALLEL(8)*/  b.client_no
             FROM REP.MZC_MEMZUC_RESULTS_SENT b
             WHERE ((RISK_CODE LIKE '3%') OR NVL(COMMISSION_AMOUNT,0) <> 0)
             AND (DATA_DATE > TO_DATE('06.08.2017', 'DD.MM.YYYY') AND DATA_DATE <= TO_DATE('30.09.2018', 'DD.MM.YYYY')) 
union 
SELECT /*+PARALLEL(8)*/  d.client_no FROM REP.REP d
            WHERE DATA_DATE > TO_DATE ('06.08.2017','DD.MM.YYYY') AND  DATA_DATE <= TO_DATE ('30.09.2018','DD.MM.YYYY') 
            AND PRODUCT_TYPE <> 3 AND DAYS_PAST_DUE > 0
union 
SELECT /*+PARALLEL(8)*/  e.client_no FROM REP.RISK_CHEQUE_DETAILS e
            WHERE DATA_DATE > TO_DATE ('06.08.2017','DD.MM.YYYY') AND  DATA_DATE <= TO_DATE ('30.09.2018','DD.MM.YYYY') 
            AND NVL(DISHONORED_CHEQUE_AMOUNT,0) <> 0
), 
CLIENT AS (
select distinct client_no from (
SELECT /*+PARALLEL(8)*/ CLIENT_NO
                FROM REP.ALL_RISK R
                 WHERE DATA_DATE BETWEEN TO_DATE('01.12.2018', 'DD.MM.YYYY') AND TO_DATE('31.12.2018', 'DD.MM.YYYY') AND R.PRODUCT_TYPE = 1
                 GROUP BY DATA_DATE, CLIENT_NO
                HAVING  SUM(R.TOTAL_BALANCE_AMOUNT_TL +
                           R.TOTAL_EXPENSE_AMOUNT_TL +
                           R.TOTAL_REDISCOUNT_AMOUNT_TL +
                           R.TOTAL_ACCRUAL_AMOUNT_TL) > 1000000  )
                minus
                select client_no FROM ELEME_LISTESI E  
)                    
SELECT /*+PARALLEL(8)*/  DISTINCT C.CLIENT_NO,
       CASE WHEN RISK_CODE LIKE '3%' THEN 1 ELSE 0 END AS TASFIYE,
       CASE WHEN NVL(COMMISSION_AMOUNT,0) <> 0 THEN 1 ELSE 0 END TEMERRUD,
       CASE WHEN GECIKME = 1 THEN 1 ELSE 0 END GECIKME,
       CASE WHEN DISHONORED_CHEQUE_AMOUNT IS NOT NULL THEN 1 ELSE 0 END ARKASI_YAZILI_CEKLER
FROM CLIENT C
LEFT JOIN (   SELECT CLIENT_NO, SUM(NVL(M.COMMISSION_AMOUNT,0)) AS COMMISSION_AMOUNT, MAX(M.RISK_CODE) AS RISK_CODE
              FROM REP.MZC_MEMZUC_RESULTS_SENT M
              WHERE M.DATA_DATE = TO_DATE('31.12.2018', 'DD.MM.YYYY')
              AND (M.RISK_CODE LIKE '3%' OR NVL(M.COMMISSION_AMOUNT,0) <> 0)
              GROUP BY CLIENT_NO
          ) M ON M.CLIENT_NO = C.CLIENT_NO
LEFT JOIN ( SELECT  /*+NO_INDEX(d)*/ DISTINCT CLIENT_NO, 1 AS GECIKME
            FROM REP.ALL_RISK d
            WHERE DATA_DATE >= TO_DATE ('01.12.2018','DD.MM.YYYY') AND  DATA_DATE <= TO_DATE ('31.12.2018','DD.MM.YYYY') 
            AND PRODUCT_TYPE <> 3 AND DAYS_PAST_DUE > 0     
          ) R ON R.CLIENT_NO = C.CLIENT_NO
LEFT JOIN (  SELECT DISTINCT CLIENT_NO, NVL(DISHONORED_CHEQUE_AMOUNT,0) AS DISHONORED_CHEQUE_AMOUNT
             FROM REP.RISK_CHEQUE_DETAILS e
             WHERE DATA_DATE >= TO_DATE ('01.12.2018','DD.MM.YYYY') AND  DATA_DATE <= TO_DATE ('31.12.2018','DD.MM.YYYY') 
             AND NVL(DISHONORED_CHEQUE_AMOUNT,0) <> 0   
          ) Q ON Q.CLIENT_NO = C.CLIENT_NO
